name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t maxmedina05/complex-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true maxmedina05/complex-test npm test

      - run: docker build -t maxmedina05/complex-client ./client
      - run: docker build -t maxmedina05/complex-nginx ./nginx
      - run: docker build -t maxmedina05/complex-server ./server
      - run: docker build -t maxmedina05/complex-worker ./worker

      # Push to Docker Hub
      - run: docker push maxmedina05/complex-client
      - run: docker push maxmedina05/complex-nginx
      - run: docker push maxmedina05/complex-server
      - run: docker push maxmedina05/complex-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: complex-demo
          environment_name: Complexdemo-env
          existing_bucket_name: elasticbeanstalk-us-west-2-798219177893
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
